[2025-04-20 09:29:44,458: INFO: main: wlcm to custm log]
[2025-04-20 09:44:09,100: INFO: main: wlcm to custm log]
[2025-04-20 09:46:46,950: INFO: main: wlcm to custm log]
[2025-04-20 09:53:58,110: INFO: main: wlcm to custm log]
[2025-04-20 10:14:53,056: INFO: main: wlcm to custm log]
[2025-04-20 10:16:14,258: INFO: main: wlcm to custm log]
[2025-04-20 10:16:23,272: INFO: main: wlcm to custm log]
[2025-04-24 23:43:46,133: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-24 23:46:48,716: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-24 23:46:48,724: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-24 23:46:48,726: INFO: common: created directory at: artifacts]
[2025-04-24 23:46:48,729: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-24 23:47:00,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-24 23:47:00,800: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-24 23:47:00,802: INFO: common: created directory at: artifacts]
[2025-04-24 23:47:00,803: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-24 23:47:06,652: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-24 23:47:06,654: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-24 23:47:06,655: INFO: common: created directory at: artifacts]
[2025-04-24 23:47:06,656: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-29 21:34:31,897: INFO: main: >>>>>>>> stage DAta Ingestion Stage started here <<<<<<<<]
[2025-04-29 21:34:31,899: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-29 21:34:31,901: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-29 21:34:31,902: INFO: common: created directory at: artifacts]
[2025-04-29 21:34:31,903: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-29 21:34:31,904: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-29 21:36:20,879: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-29 21:36:40,540: INFO: main: >>>>>>>>> stage DAta Ingestion Stage completed <<<<<<<<<

X=======================================================X]
[2025-05-01 15:16:40,027: INFO: main: >>>>>>>> stage Data Ingestion Stage started here <<<<<<<<]
[2025-05-01 15:16:40,042: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-01 15:16:40,044: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-01 15:16:40,051: INFO: common: created directory at: artifacts]
[2025-05-01 15:16:40,051: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-01 15:16:40,052: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-01 15:19:51,362: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-01 15:20:06,367: INFO: main: >>>>>>>>> stage Data Ingestion Stage completed <<<<<<<<<

X=======================================================X]
[2025-05-01 16:32:49,808: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-01 16:32:49,824: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-01 16:32:49,826: INFO: common: created directory at: artifacts]
[2025-05-01 16:34:22,321: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-01 16:34:22,324: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-01 16:34:22,325: INFO: common: created directory at: artifacts]
[2025-05-01 16:34:22,327: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-01 16:34:32,781: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-01 16:38:59,992: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-01 16:38:59,996: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-01 16:38:59,998: INFO: common: created directory at: artifacts]
[2025-05-01 16:38:59,999: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-01 16:39:00,406: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-01 16:40:52,656: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-01 16:40:52,658: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-01 16:40:52,659: INFO: common: created directory at: artifacts]
[2025-05-01 16:40:52,660: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-01 16:40:53,083: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-01 16:45:42,153: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-01 16:45:42,155: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-01 16:45:42,156: INFO: common: created directory at: artifacts]
[2025-05-01 16:45:42,158: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-01 16:45:42,624: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-01 16:45:57,857: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-01 16:45:57,861: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-01 16:45:57,862: INFO: common: created directory at: artifacts]
[2025-05-01 16:45:57,863: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-01 16:45:58,162: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-01 17:09:12,808: INFO: main: >>>>>>>> stage Data Ingestion Stage started here <<<<<<<<]
[2025-05-01 17:09:12,811: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-01 17:09:12,812: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-01 17:09:12,812: INFO: common: created directory at: artifacts]
[2025-05-01 17:09:12,813: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-01 17:09:12,813: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-01 17:12:29,730: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-01 17:12:49,391: INFO: main: >>>>>>>>> stage Data Ingestion Stage completed <<<<<<<<<

X=======================================================X]
[2025-05-01 17:12:49,391: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-01 17:12:49,391: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-01 17:12:49,391: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-01 17:12:49,391: INFO: common: created directory at: artifacts]
[2025-05-01 17:12:49,391: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-01 17:12:51,803: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-01 17:12:52,130: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-03 16:50:26,088: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-03 16:50:26,106: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-03 16:50:26,107: INFO: common: created directory at: artifacts]
[2025-05-03 16:51:32,045: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-03 16:51:32,046: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-03 16:51:32,047: INFO: common: created directory at: artifacts]
[2025-05-03 16:52:09,204: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-03 16:52:09,204: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-03 16:52:09,204: INFO: common: created directory at: artifacts]
[2025-05-03 16:53:06,425: INFO: stage_03_model_training: >>>>>>>> stage Model Training Stage started here <<<<<<<<]
[2025-05-03 16:53:06,425: ERROR: stage_03_model_training: Training.__init__() missing 1 required positional argument: 'config']
Traceback (most recent call last):
  File "d:\E2E Proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 26, in <module>
    obj = Training()
TypeError: Training.__init__() missing 1 required positional argument: 'config'
[2025-05-03 16:55:16,396: INFO: stage_03_model_training: >>>>>>>> stage Model Training Stage started here <<<<<<<<]
[2025-05-03 16:55:16,396: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-03 16:55:16,396: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-03 16:55:16,396: INFO: common: created directory at: artifacts]
[2025-05-03 16:55:16,396: INFO: common: created directory at: artifacts\trainig]
[2025-05-03 16:55:16,396: ERROR: stage_03_model_training: TrainingConfig.__init__() missing 1 required positional argument: 'training_data']
Traceback (most recent call last):
  File "d:\E2E Proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 27, in <module>
    obj.main()
  File "d:\E2E Proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 15, in main
    training_config = config.get_training_config()
  File "d:\e2e proj\src\cnnClassifier\config\configuration.py", line 72, in get_training_config
    training_config = TrainingConfig(
TypeError: TrainingConfig.__init__() missing 1 required positional argument: 'training_data'
[2025-05-03 16:55:32,485: INFO: main: >>>>>>>> stage Data Ingestion Stage started here <<<<<<<<]
[2025-05-03 16:55:32,485: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-03 16:55:32,485: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-03 16:55:32,485: INFO: common: created directory at: artifacts]
[2025-05-03 16:55:32,485: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-03 16:55:32,485: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-03 17:10:52,570: ERROR: main: ('Connection broken: IncompleteRead(498396667 bytes read, 1129522641 more expected)', IncompleteRead(498396667 bytes read, 1129522641 more expected))]
Traceback (most recent call last):
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 754, in _error_catcher
    yield
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 900, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(498396667 bytes read, 1129522641 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 1066, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 983, in read
    data = self._raw_read(amt)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 878, in _raw_read
    with self._error_catcher():
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 778, in _error_catcher
    raise ProtocolError(arg, e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(498396667 bytes read, 1129522641 more expected)', IncompleteRead(498396667 bytes read, 1129522641 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 13, in <module>
    obj.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "d:\e2e proj\src\cnnClassifier\components\data_ingestion.py", line 31, in download_file
    raise e
  File "d:\e2e proj\src\cnnClassifier\components\data_ingestion.py", line 26, in download_file
    gdown.download(prefix+file_id, zip_download_dir)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\gdown\download.py", line 368, in download
    for chunk in res.iter_content(chunk_size=CHUNK_SIZE):
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(498396667 bytes read, 1129522641 more expected)', IncompleteRead(498396667 bytes read, 1129522641 more expected))
[2025-05-03 17:11:27,048: INFO: main: >>>>>>>> stage Data Ingestion Stage started here <<<<<<<<]
[2025-05-03 17:11:27,050: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-03 17:11:27,052: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-03 17:11:27,052: INFO: common: created directory at: artifacts]
[2025-05-03 17:11:27,052: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-03 17:11:27,053: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-03 17:13:21,673: INFO: main: >>>>>>>> stage Data Ingestion Stage started here <<<<<<<<]
[2025-05-03 17:13:21,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-03 17:13:21,673: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-03 17:13:21,673: INFO: common: created directory at: artifacts]
[2025-05-03 17:13:21,673: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-03 17:13:21,673: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-03 17:16:10,140: ERROR: main: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))]
Traceback (most recent call last):
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 13, in <module>
    obj.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "d:\e2e proj\src\cnnClassifier\components\data_ingestion.py", line 31, in download_file
    raise e
  File "d:\e2e proj\src\cnnClassifier\components\data_ingestion.py", line 26, in download_file
    gdown.download(prefix+file_id, zip_download_dir)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\gdown\download.py", line 202, in download
    res = sess.get(url, stream=True, verify=verify)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
[2025-05-03 17:26:23,441: INFO: main: >>>>>>>> stage Data Ingestion Stage started here <<<<<<<<]
[2025-05-03 17:26:23,441: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-03 17:26:23,457: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-03 17:26:23,457: INFO: common: created directory at: artifacts]
[2025-05-03 17:26:23,458: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-03 17:26:23,459: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-03 17:47:32,305: ERROR: main: ('Connection broken: IncompleteRead(1083873001 bytes read, 544046307 more expected)', IncompleteRead(1083873001 bytes read, 544046307 more expected))]
Traceback (most recent call last):
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 754, in _error_catcher
    yield
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 900, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(1083873001 bytes read, 544046307 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 1066, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 983, in read
    data = self._raw_read(amt)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 878, in _raw_read
    with self._error_catcher():
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 778, in _error_catcher
    raise ProtocolError(arg, e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(1083873001 bytes read, 544046307 more expected)', IncompleteRead(1083873001 bytes read, 544046307 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 13, in <module>
    obj.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "d:\e2e proj\src\cnnClassifier\components\data_ingestion.py", line 31, in download_file
    raise e
  File "d:\e2e proj\src\cnnClassifier\components\data_ingestion.py", line 26, in download_file
    gdown.download(prefix+file_id, zip_download_dir)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\gdown\download.py", line 368, in download
    for chunk in res.iter_content(chunk_size=CHUNK_SIZE):
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(1083873001 bytes read, 544046307 more expected)', IncompleteRead(1083873001 bytes read, 544046307 more expected))
[2025-05-09 21:10:53,128: INFO: main: >>>>>>>> stage Data Ingestion Stage started here <<<<<<<<]
[2025-05-09 21:10:53,140: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-09 21:10:53,154: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-09 21:10:53,155: INFO: common: created directory at: artifacts]
[2025-05-09 21:10:53,156: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-09 21:10:53,157: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-09 21:14:01,545: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-09 21:14:17,220: INFO: main: >>>>>>>>> stage Data Ingestion Stage completed <<<<<<<<<

X=======================================================X]
[2025-05-09 21:14:17,220: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-09 21:14:17,220: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-09 21:14:17,220: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-09 21:14:17,220: INFO: common: created directory at: artifacts]
[2025-05-09 21:14:17,220: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-09 21:14:19,836: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-09 21:14:20,123: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-09 21:14:20,123: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-09 21:14:20,123: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-09 21:14:20,123: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-09 21:14:20,123: INFO: common: created directory at: artifacts]
[2025-05-09 21:14:20,123: INFO: common: created directory at: artifacts\trainig]
[2025-05-09 21:14:20,123: ERROR: main: TrainingConfig.__init__() missing 1 required positional argument: 'training_data']
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 34, in <module>
    training_model.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 15, in main
    training_config = config.get_training_config()
  File "d:\e2e proj\src\cnnClassifier\config\configuration.py", line 72, in get_training_config
    training_config = TrainingConfig(
TypeError: TrainingConfig.__init__() missing 1 required positional argument: 'training_data'
[2025-05-09 21:25:07,671: INFO: main: >>>>>>>> stage Data Ingestion Stage started here <<<<<<<<]
[2025-05-09 21:25:07,682: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-09 21:25:07,683: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-09 21:25:07,684: INFO: common: created directory at: artifacts]
[2025-05-09 21:25:07,684: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-09 21:25:07,685: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-09 21:28:16,071: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-09 21:28:30,712: INFO: main: >>>>>>>>> stage Data Ingestion Stage completed <<<<<<<<<

X=======================================================X]
[2025-05-09 21:28:30,712: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-09 21:28:30,716: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-09 21:28:30,716: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-09 21:28:30,718: INFO: common: created directory at: artifacts]
[2025-05-09 21:28:30,718: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-09 21:28:31,710: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-09 21:28:32,023: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-09 21:28:32,023: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-09 21:28:32,023: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-09 21:28:32,023: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-09 21:28:32,023: INFO: common: created directory at: artifacts]
[2025-05-09 21:28:32,023: INFO: common: created directory at: artifacts\trainig]
[2025-05-09 21:28:32,663: ERROR: main: unsupported operand type(s) for ** or pow(): 'bool' and 'dict']
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 34, in <module>
    training_model.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_genrator()
  File "d:\e2e proj\src\cnnClassifier\components\training_data.py", line 38, in train_valid_genrator
    shuffle = False
TypeError: unsupported operand type(s) for ** or pow(): 'bool' and 'dict'
[2025-05-09 21:32:33,233: INFO: main: >>>>>>>> stage Data Ingestion Stage started here <<<<<<<<]
[2025-05-09 21:32:33,233: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-09 21:32:33,233: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-09 21:32:33,233: INFO: common: created directory at: artifacts]
[2025-05-09 21:32:33,233: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-09 21:32:33,233: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-09 21:36:00,842: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-09 21:36:16,458: INFO: main: >>>>>>>>> stage Data Ingestion Stage completed <<<<<<<<<

X=======================================================X]
[2025-05-09 21:36:16,458: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-09 21:36:16,463: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-09 21:36:16,463: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-09 21:36:16,463: INFO: common: created directory at: artifacts]
[2025-05-09 21:36:16,463: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-09 21:36:17,452: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-09 21:36:18,658: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-09 21:36:18,658: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-09 21:36:18,674: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-09 21:36:18,674: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-09 21:36:18,674: INFO: common: created directory at: artifacts]
[2025-05-09 21:36:18,674: INFO: common: created directory at: artifacts\trainig]
[2025-05-09 21:36:18,949: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 34, in <module>
    training_model.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_genrator()
  File "d:\e2e proj\src\cnnClassifier\components\training_data.py", line 35, in train_valid_genrator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 1650, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2025-05-24 16:21:40,838: INFO: main: >>>>>>>> stage Data Ingestion Stage started here <<<<<<<<]
[2025-05-24 16:21:40,855: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 16:21:40,869: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 16:21:40,871: INFO: common: created directory at: artifacts]
[2025-05-24 16:21:40,872: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-24 16:21:40,873: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-24 16:23:24,258: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-24 16:23:51,947: INFO: main: >>>>>>>>> stage Data Ingestion Stage completed <<<<<<<<<

X=======================================================X]
[2025-05-24 16:23:51,948: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-24 16:23:51,953: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 16:23:51,954: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 16:23:51,956: INFO: common: created directory at: artifacts]
[2025-05-24 16:23:51,957: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-24 16:23:56,361: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-24 16:23:56,808: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-24 16:23:56,808: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-24 16:23:56,811: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 16:23:56,813: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 16:23:56,813: INFO: common: created directory at: artifacts]
[2025-05-24 16:23:56,814: INFO: common: created directory at: artifacts\trainig]
[2025-05-24 16:23:57,212: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 34, in <module>
    training_model.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_genrator()
  File "d:\e2e proj\src\cnnClassifier\components\training_data.py", line 35, in train_valid_genrator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 1650, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2025-05-24 17:06:18,970: INFO: main: >>>>>>>> stage Data Ingestion Stage started here <<<<<<<<]
[2025-05-24 17:06:18,980: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:06:18,980: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:06:18,980: INFO: common: created directory at: artifacts]
[2025-05-24 17:06:18,990: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-24 17:06:18,992: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/kidney-ct-scan-image.zip]
[2025-05-24 17:07:33,508: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/kidney-ct-scan-image.zip]
[2025-05-24 17:08:00,337: INFO: main: >>>>>>>>> stage Data Ingestion Stage completed <<<<<<<<<

X=======================================================X]
[2025-05-24 17:08:00,337: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-24 17:08:00,337: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:08:00,337: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:08:00,337: INFO: common: created directory at: artifacts]
[2025-05-24 17:08:00,337: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-24 17:08:02,794: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-24 17:08:03,146: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-24 17:08:03,146: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-24 17:08:03,146: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:08:03,161: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:08:03,161: INFO: common: created directory at: artifacts]
[2025-05-24 17:08:03,161: INFO: common: created directory at: artifacts\training]
[2025-05-24 17:08:03,643: ERROR: main: 'TrainingConfig' object has no attribute 'params_is_augmentation']
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 34, in <module>
    training_model.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_genrator()
  File "d:\e2e proj\src\cnnClassifier\components\training_data.py", line 42, in train_valid_genrator
    if self.config.params_is_augmentation:
AttributeError: 'TrainingConfig' object has no attribute 'params_is_augmentation'
[2025-05-24 17:11:05,056: INFO: main: >>>>>>>> stage Data Ingestion Stage started here <<<<<<<<]
[2025-05-24 17:11:05,058: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:11:05,059: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:11:05,060: INFO: common: created directory at: artifacts]
[2025-05-24 17:11:05,060: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-24 17:11:05,061: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/kidney-ct-scan-image.zip]
[2025-05-24 17:12:56,011: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/kidney-ct-scan-image.zip]
[2025-05-24 17:13:11,226: INFO: main: >>>>>>>>> stage Data Ingestion Stage completed <<<<<<<<<

X=======================================================X]
[2025-05-24 17:13:11,226: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-24 17:13:11,226: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:13:11,226: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:13:11,226: INFO: common: created directory at: artifacts]
[2025-05-24 17:13:11,226: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-24 17:13:12,244: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-24 17:13:12,962: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-24 17:13:12,962: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-24 17:13:12,962: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:13:12,962: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:13:12,962: INFO: common: created directory at: artifacts]
[2025-05-24 17:13:12,962: INFO: common: created directory at: artifacts\training]
[2025-05-24 17:13:12,962: ERROR: main: TrainingConfig.__init__() got an unexpected keyword argument 'params_is_augmetation']
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 34, in <module>
    training_model.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 15, in main
    training_config = config.get_training_config()
  File "d:\e2e proj\src\cnnClassifier\config\configuration.py", line 72, in get_training_config
    training_config = TrainingConfig(
TypeError: TrainingConfig.__init__() got an unexpected keyword argument 'params_is_augmetation'
[2025-05-24 17:17:11,228: INFO: main: >>>>>>>> stage Data Ingestion Stage started here <<<<<<<<]
[2025-05-24 17:17:11,228: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:17:11,228: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:17:11,228: INFO: common: created directory at: artifacts]
[2025-05-24 17:17:11,228: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-24 17:17:11,228: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/kidney-ct-scan-image.zip]
[2025-05-24 17:18:35,493: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/kidney-ct-scan-image.zip]
[2025-05-24 17:18:55,655: INFO: main: >>>>>>>>> stage Data Ingestion Stage completed <<<<<<<<<

X=======================================================X]
[2025-05-24 17:18:55,655: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-24 17:18:55,658: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:18:55,659: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:18:55,660: INFO: common: created directory at: artifacts]
[2025-05-24 17:18:55,660: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-24 17:18:57,073: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-24 17:18:58,078: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-24 17:18:58,078: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-24 17:18:58,082: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:18:58,085: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:18:58,085: INFO: common: created directory at: artifacts]
[2025-05-24 17:18:58,090: INFO: common: created directory at: artifacts\training]
[2025-05-24 17:18:59,231: ERROR: main: Training.train() missing 1 required positional argument: 'callback_list']
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 34, in <module>
    training_model.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train()
TypeError: Training.train() missing 1 required positional argument: 'callback_list'
[2025-05-24 17:47:51,333: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-24 17:47:51,334: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:47:51,336: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:47:51,336: INFO: common: created directory at: artifacts]
[2025-05-24 17:47:51,336: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-24 17:47:52,475: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-24 17:47:52,735: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-24 17:47:52,735: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-24 17:47:52,735: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:47:52,735: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:47:52,735: INFO: common: created directory at: artifacts]
[2025-05-24 17:47:52,735: INFO: common: created directory at: artifacts\training]
[2025-05-24 17:47:53,334: ERROR: main: Training.train() missing 1 required positional argument: 'callback_list']
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 34, in <module>
    training_model.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train()
TypeError: Training.train() missing 1 required positional argument: 'callback_list'
[2025-05-24 17:49:34,143: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-24 17:49:34,144: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:49:34,146: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:49:34,146: INFO: common: created directory at: artifacts]
[2025-05-24 17:49:34,147: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-24 17:49:35,173: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-24 17:49:35,475: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-24 17:49:35,475: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-24 17:49:35,477: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:49:35,478: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:49:35,478: INFO: common: created directory at: artifacts]
[2025-05-24 17:49:35,479: INFO: common: created directory at: artifacts\training]
[2025-05-24 17:49:36,084: ERROR: main: 'Training' object has no attribute 'train']
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 34, in <module>
    training_model.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train()
AttributeError: 'Training' object has no attribute 'train'
[2025-05-24 17:53:56,909: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-24 17:53:56,909: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:53:56,909: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:53:56,909: INFO: common: created directory at: artifacts]
[2025-05-24 17:53:56,909: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-24 17:53:57,950: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-24 17:53:58,247: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-24 17:53:58,247: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-24 17:53:58,249: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:53:58,250: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:53:58,250: INFO: common: created directory at: artifacts]
[2025-05-24 17:53:58,251: INFO: common: created directory at: artifacts\training]
[2025-05-24 17:53:58,859: ERROR: main: 'Training' object has no attribute 'train']
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 34, in <module>
    training_model.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train()
AttributeError: 'Training' object has no attribute 'train'
[2025-05-24 17:55:05,910: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-24 17:55:05,910: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:55:05,910: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:55:05,910: INFO: common: created directory at: artifacts]
[2025-05-24 17:55:05,910: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-24 17:55:06,834: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-24 17:55:07,096: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-24 17:55:07,096: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-24 17:55:07,096: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:55:07,096: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:55:07,096: INFO: common: created directory at: artifacts]
[2025-05-24 17:55:07,096: INFO: common: created directory at: artifacts\training]
[2025-05-24 17:55:07,342: ERROR: main: 'Training' object has no attribute 'train_valid_genrator']
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 34, in <module>
    training_model.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_genrator()
AttributeError: 'Training' object has no attribute 'train_valid_genrator'
[2025-05-24 17:58:05,952: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-24 17:58:05,954: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:58:05,955: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:58:05,956: INFO: common: created directory at: artifacts]
[2025-05-24 17:58:05,956: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-24 17:58:06,898: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-24 17:58:07,173: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-24 17:58:07,173: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-24 17:58:07,173: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 17:58:07,176: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 17:58:07,176: INFO: common: created directory at: artifacts]
[2025-05-24 17:58:07,176: INFO: common: created directory at: artifacts\training]
[2025-05-24 18:11:27,934: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-24 18:11:27,947: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 18:11:27,960: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 18:11:27,960: INFO: common: created directory at: artifacts]
[2025-05-24 18:11:27,960: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-24 18:11:30,041: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-24 18:11:30,854: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-24 18:11:30,854: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-24 18:11:30,854: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 18:11:30,854: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 18:11:30,854: INFO: common: created directory at: artifacts]
[2025-05-24 18:11:30,854: INFO: common: created directory at: artifacts\training]
[2025-05-24 18:47:31,518: INFO: main: >>>>>>>>>>>> Stage Model Training COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-24 18:58:29,060: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-24 18:58:29,060: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 18:58:29,060: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 18:58:29,060: INFO: common: created directory at: artifacts]
[2025-05-24 18:58:29,060: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-24 18:58:30,031: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-24 18:58:30,318: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-24 18:58:30,318: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-24 18:58:30,318: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 18:58:30,318: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 18:58:30,318: INFO: common: created directory at: artifacts]
[2025-05-24 18:58:30,318: INFO: common: created directory at: artifacts\training]
[2025-05-24 19:03:13,245: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-24 19:03:13,245: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 19:03:13,245: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 19:03:13,245: INFO: common: created directory at: artifacts]
[2025-05-24 19:03:13,245: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-24 19:03:14,134: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-24 19:03:14,402: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-24 19:03:14,402: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-24 19:03:14,418: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 19:03:14,418: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 19:03:14,418: INFO: common: created directory at: artifacts]
[2025-05-24 19:03:14,418: INFO: common: created directory at: artifacts\training]
[2025-05-24 19:07:00,985: ERROR: main: Graph execution error:

2 root error(s) found.
  (0) UNKNOWN:  FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\Cyst\\Cyst- (819).jpg'
Traceback (most recent call last):

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\ops\script_ops.py", line 271, in __call__
    ret = func(*args)

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1035, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\data_adapter.py", line 903, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\data_adapter.py", line 1050, in generator_fn
    yield x[i]

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 116, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 370, in _get_batches_of_transformed_samples
    img = image_utils.load_img(

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\Cyst\\Cyst- (819).jpg'


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_2]]
  (1) UNKNOWN:  FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\Cyst\\Cyst- (819).jpg'
Traceback (most recent call last):

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\ops\script_ops.py", line 271, in __call__
    ret = func(*args)

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1035, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\data_adapter.py", line 903, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\data_adapter.py", line 1050, in generator_fn
    yield x[i]

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 116, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 370, in _get_batches_of_transformed_samples
    img = image_utils.load_img(

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\Cyst\\Cyst- (819).jpg'


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_1909]]
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 34, in <module>
    training_model.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train()
  File "d:\e2e proj\src\cnnClassifier\components\training_data.py", line 77, in train
    self.model.fit(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

2 root error(s) found.
  (0) UNKNOWN:  FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\Cyst\\Cyst- (819).jpg'
Traceback (most recent call last):

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\ops\script_ops.py", line 271, in __call__
    ret = func(*args)

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1035, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\data_adapter.py", line 903, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\data_adapter.py", line 1050, in generator_fn
    yield x[i]

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 116, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 370, in _get_batches_of_transformed_samples
    img = image_utils.load_img(

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\Cyst\\Cyst- (819).jpg'


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_2]]
  (1) UNKNOWN:  FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\Cyst\\Cyst- (819).jpg'
Traceback (most recent call last):

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\ops\script_ops.py", line 271, in __call__
    ret = func(*args)

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1035, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\data_adapter.py", line 903, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\data_adapter.py", line 1050, in generator_fn
    yield x[i]

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 116, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 370, in _get_batches_of_transformed_samples
    img = image_utils.load_img(

  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\\Cyst\\Cyst- (819).jpg'


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_1909]
[2025-05-24 19:07:55,386: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-24 19:07:55,386: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 19:07:55,386: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 19:07:55,386: INFO: common: created directory at: artifacts]
[2025-05-24 19:07:55,386: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-24 19:07:56,261: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-24 19:07:56,556: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-24 19:07:56,556: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-24 19:07:56,556: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-24 19:07:56,572: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-24 19:07:56,572: INFO: common: created directory at: artifacts]
[2025-05-24 19:07:56,572: INFO: common: created directory at: artifacts\training]
[2025-05-24 19:41:59,964: INFO: main: >>>>>>>>>>>> Stage Model Training COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-27 22:52:17,701: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-27 22:52:17,718: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-27 22:52:17,724: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-27 22:52:17,733: INFO: common: created directory at: artifacts]
[2025-05-27 22:52:17,733: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-27 22:52:20,013: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-27 22:52:20,442: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-27 22:52:20,442: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-27 22:52:20,445: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-27 22:52:20,447: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-27 22:52:20,447: INFO: common: created directory at: artifacts]
[2025-05-27 22:52:20,449: INFO: common: created directory at: artifacts\training]
[2025-05-27 23:01:02,387: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-27 23:01:02,400: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-27 23:01:02,414: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-27 23:01:02,415: INFO: common: created directory at: artifacts]
[2025-05-27 23:01:02,416: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-27 23:01:04,913: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-27 23:01:05,464: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-27 23:01:05,464: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-27 23:01:05,470: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-27 23:01:05,473: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-27 23:01:05,474: INFO: common: created directory at: artifacts]
[2025-05-27 23:01:05,476: INFO: common: created directory at: artifacts\training]
[2025-05-27 23:07:00,007: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-27 23:07:00,009: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-27 23:07:00,021: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-27 23:07:00,023: INFO: common: created directory at: artifacts]
[2025-05-27 23:07:00,023: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-27 23:07:00,943: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-27 23:07:01,240: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-27 23:07:01,240: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-27 23:07:01,242: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-27 23:07:01,243: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-27 23:07:01,244: INFO: common: created directory at: artifacts]
[2025-05-27 23:07:01,244: INFO: common: created directory at: artifacts\training]
[2025-05-27 23:36:29,069: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-27 23:36:29,083: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-27 23:36:29,095: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-27 23:36:29,096: INFO: common: created directory at: artifacts]
[2025-05-27 23:36:29,097: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-27 23:36:30,953: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-27 23:36:31,522: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-27 23:36:31,522: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-27 23:36:31,524: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-27 23:36:31,526: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-27 23:36:31,526: INFO: common: created directory at: artifacts]
[2025-05-27 23:36:31,527: INFO: common: created directory at: artifacts\training]
[2025-05-28 00:27:20,811: INFO: main: >>>>>>>>>>>> Stage Model Training COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-28 00:27:20,811: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-28 00:27:20,813: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 00:27:20,815: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 00:27:20,816: INFO: common: created directory at: artifacts]
[2025-05-28 00:27:20,818: ERROR: main: No file or directory found at aretifacts/training/model.h5]
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 47, in <module>
    model_eval.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_04_model_eval.py", line 18, in main
    evaluation.evaluation()
  File "d:\e2e proj\src\cnnClassifier\components\model_eval.py", line 47, in evaluation
    self.model = self.load_model(self.config.path_of_model)
  File "d:\e2e proj\src\cnnClassifier\components\model_eval.py", line 43, in load_model
    return tf.keras.models.load_model(path)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\saving\save.py", line 226, in load_model
    raise IOError(
OSError: No file or directory found at aretifacts/training/model.h5
[2025-05-28 00:29:46,171: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-28 00:29:46,175: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 00:29:46,177: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 00:29:46,177: INFO: common: created directory at: artifacts]
[2025-05-28 00:29:46,178: ERROR: main: No file or directory found at aretifacts/training/model.h5]
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 47, in <module>
    model_eval.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_04_model_eval.py", line 18, in main
    evaluation.evaluation()
  File "d:\e2e proj\src\cnnClassifier\components\model_eval.py", line 47, in evaluation
    self.model = self.load_model(self.config.path_of_model)
  File "d:\e2e proj\src\cnnClassifier\components\model_eval.py", line 43, in load_model
    return tf.keras.models.load_model(path)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\saving\save.py", line 226, in load_model
    raise IOError(
OSError: No file or directory found at aretifacts/training/model.h5
[2025-05-28 00:33:53,550: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-28 00:33:53,552: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 00:33:53,554: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 00:33:53,554: INFO: common: created directory at: artifacts]
[2025-05-28 00:33:54,594: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts/data_ingestion/kideny-ct-scaan-image']
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 47, in <module>
    model_eval.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_04_model_eval.py", line 18, in main
    evaluation.evaluation()
  File "d:\e2e proj\src\cnnClassifier\components\model_eval.py", line 48, in evaluation
    self._valid_generator()
  File "d:\e2e proj\src\cnnClassifier\components\model_eval.py", line 33, in _valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 1650, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts/data_ingestion/kideny-ct-scaan-image'
[2025-05-28 00:35:13,673: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-28 00:35:13,675: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 00:35:13,676: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 00:35:13,677: INFO: common: created directory at: artifacts]
[2025-05-28 00:35:14,773: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts/data_ingestion/kideny-ct-scan-image']
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 47, in <module>
    model_eval.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_04_model_eval.py", line 18, in main
    evaluation.evaluation()
  File "d:\e2e proj\src\cnnClassifier\components\model_eval.py", line 48, in evaluation
    self._valid_generator()
  File "d:\e2e proj\src\cnnClassifier\components\model_eval.py", line 33, in _valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 1650, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts/data_ingestion/kideny-ct-scan-image'
[2025-05-28 00:35:57,066: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-28 00:35:57,069: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 00:35:57,070: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 00:35:57,071: INFO: common: created directory at: artifacts]
[2025-05-28 00:37:31,625: INFO: common: json file saved at: scores.json]
[2025-05-28 00:37:31,626: INFO: common: json file saved at: scores.json]
[2025-05-28 00:37:31,626: INFO: main: >>>>>>>>>>>> Stage Model Evaluation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-28 19:18:34,112: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-28 19:18:34,112: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 19:18:34,126: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 19:18:34,126: INFO: common: created directory at: artifacts]
[2025-05-28 19:20:01,094: INFO: common: json file saved at: scores.json]
[2025-05-28 19:20:01,094: INFO: common: json file saved at: scores.json]
[2025-05-28 19:20:01,094: INFO: main: >>>>>>>>>>>> Stage Model Evaluation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-28 19:25:11,070: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-28 19:25:11,082: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 19:25:11,084: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 19:25:11,085: INFO: common: created directory at: artifacts]
[2025-05-28 19:26:40,068: INFO: stage_04_model_eval: *******************]
[2025-05-28 19:26:40,069: INFO: stage_04_model_eval: >>>>>> stage Evaluation stage started <<<<<<]
[2025-05-28 19:26:40,071: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 19:26:40,072: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 19:26:40,073: INFO: common: created directory at: artifacts]
[2025-05-28 19:28:42,277: INFO: common: json file saved at: scores.json]
[2025-05-28 19:28:42,278: INFO: common: json file saved at: scores.json]
[2025-05-28 19:28:44,373: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-05-28 19:28:45,272: INFO: builder_impl: Assets written to: C:\Users\Gourav\AppData\Local\Temp\tmpgj1jd1sr\model\data\model\assets]
[2025-05-28 19:29:05,066: INFO: stage_04_model_eval: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-05-28 19:42:45,697: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-28 19:42:45,697: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 19:42:45,713: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 19:42:45,713: INFO: common: created directory at: artifacts]
[2025-05-28 19:44:09,094: INFO: common: json file saved at: scores.json]
[2025-05-28 19:44:09,094: INFO: common: json file saved at: scores.json]
[2025-05-28 19:44:10,487: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-05-28 19:44:11,709: INFO: builder_impl: Assets written to: C:\Users\Gourav\AppData\Local\Temp\tmplrbu9ozy\model\data\model\assets]
[2025-05-28 19:44:21,334: INFO: main: >>>>>>>>>>>> Stage Model Evaluation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-28 19:45:59,228: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-28 19:45:59,228: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 19:45:59,244: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 19:45:59,244: INFO: common: created directory at: artifacts]
[2025-05-28 19:47:26,370: INFO: common: json file saved at: scores.json]
[2025-05-28 19:47:26,370: INFO: common: json file saved at: scores.json]
[2025-05-28 19:47:27,746: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-05-28 19:47:28,537: INFO: builder_impl: Assets written to: C:\Users\Gourav\AppData\Local\Temp\tmp2bs9cyzd\model\data\model\assets]
[2025-05-28 19:47:37,459: INFO: main: >>>>>>>>>>>> Stage Model Evaluation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-30 00:51:44,162: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-30 00:51:44,179: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-30 00:51:44,184: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-30 00:51:44,198: INFO: common: created directory at: artifacts]
[2025-05-30 00:53:10,093: INFO: common: json file saved at: scores.json]
[2025-05-30 00:53:10,098: INFO: common: json file saved at: scores.json]
[2025-05-30 00:53:11,921: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-05-30 00:53:12,858: INFO: builder_impl: Assets written to: C:\Users\Gourav\AppData\Local\Temp\tmprar07pty\model\data\model\assets]
[2025-05-30 00:53:26,730: INFO: main: >>>>>>>>>>>> Stage Model Evaluation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-31 14:42:57,880: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-31 14:42:57,883: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 14:42:57,886: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 14:42:57,887: INFO: common: created directory at: artifacts]
[2025-05-31 14:44:40,307: INFO: common: json file saved at: scores.json]
[2025-05-31 14:44:40,309: INFO: common: json file saved at: scores.json]
[2025-05-31 14:44:42,545: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-05-31 14:44:43,317: INFO: builder_impl: Assets written to: C:\Users\Gourav\AppData\Local\Temp\tmpqt2gnzvu\model\data\model\assets]
[2025-05-31 14:44:55,570: INFO: main: >>>>>>>>>>>> Stage Model Evaluation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-31 17:01:23,070: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 401 Unauthorized"]
[2025-05-31 17:02:51,535: INFO: _client: HTTP Request: POST https://dagshub.com/login/oauth/middleman "HTTP/1.1 200 OK"]
[2025-05-31 17:02:52,017: INFO: _client: HTTP Request: POST https://dagshub.com/login/oauth/access_token "HTTP/1.1 200 OK"]
[2025-05-31 17:02:52,487: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 17:02:52,498: INFO: helpers: Accessing as gourav7-7]
[2025-05-31 17:02:53,014: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/gourav7-7/E2E-Proj "HTTP/1.1 200 OK"]
[2025-05-31 17:02:53,464: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 17:02:53,466: INFO: helpers: Initialized MLflow to track repo "gourav7-7/E2E-Proj"]
[2025-05-31 17:02:53,466: INFO: helpers: Repository gourav7-7/E2E-Proj initialized!]
[2025-05-31 17:02:53,475: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-31 17:02:53,475: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 17:02:53,486: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 17:02:53,489: INFO: common: created directory at: artifacts]
[2025-05-31 17:04:26,165: INFO: common: json file saved at: scores.json]
[2025-05-31 17:04:26,165: INFO: common: json file saved at: scores.json]
[2025-05-31 17:04:29,956: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-05-31 17:04:30,686: INFO: builder_impl: Assets written to: C:\Users\Gourav\AppData\Local\Temp\tmpg07_35s5\model\data\model\assets]
[2025-05-31 17:05:52,515: INFO: main: >>>>>>>>>>>> Stage Model Evaluation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-31 17:17:08,457: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 17:17:08,463: INFO: helpers: Accessing as gourav7-7]
[2025-05-31 17:17:08,985: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/gourav7-7/E2E-Proj "HTTP/1.1 200 OK"]
[2025-05-31 17:17:09,423: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 17:17:09,429: INFO: helpers: Initialized MLflow to track repo "gourav7-7/E2E-Proj"]
[2025-05-31 17:17:09,433: INFO: helpers: Repository gourav7-7/E2E-Proj initialized!]
[2025-05-31 17:17:09,441: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-31 17:17:09,445: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 17:17:09,449: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 17:17:09,451: INFO: common: created directory at: artifacts]
[2025-05-31 17:18:53,133: INFO: common: json file saved at: scores.json]
[2025-05-31 17:18:53,134: INFO: common: json file saved at: scores.json]
[2025-05-31 17:18:55,915: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-05-31 17:18:56,708: INFO: builder_impl: Assets written to: C:\Users\Gourav\AppData\Local\Temp\tmpsbqh9b3o\model\data\model\assets]
[2025-05-31 17:20:14,218: INFO: main: >>>>>>>>>>>> Stage Model Evaluation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-31 17:25:48,807: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 17:25:48,815: INFO: helpers: Accessing as gourav7-7]
[2025-05-31 17:25:49,317: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/gourav7-7/E2E-Proj "HTTP/1.1 200 OK"]
[2025-05-31 17:25:49,806: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 17:25:49,811: INFO: helpers: Initialized MLflow to track repo "gourav7-7/E2E-Proj"]
[2025-05-31 17:25:49,814: INFO: helpers: Repository gourav7-7/E2E-Proj initialized!]
[2025-05-31 17:25:49,819: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-31 17:25:49,826: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 17:25:49,831: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 17:25:49,832: INFO: common: created directory at: artifacts]
[2025-05-31 17:25:49,833: INFO: common: created directory at: artifacts\training]
[2025-05-31 20:49:28,491: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 20:49:28,491: INFO: helpers: Accessing as gourav7-7]
[2025-05-31 20:49:28,945: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/gourav7-7/E2E-Proj "HTTP/1.1 200 OK"]
[2025-05-31 20:49:29,446: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 20:49:29,446: INFO: helpers: Initialized MLflow to track repo "gourav7-7/E2E-Proj"]
[2025-05-31 20:49:29,446: INFO: helpers: Repository gourav7-7/E2E-Proj initialized!]
[2025-05-31 20:49:29,466: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-31 20:49:29,469: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 20:49:29,470: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 20:49:29,471: INFO: common: created directory at: artifacts]
[2025-05-31 20:49:31,639: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-31 20:49:31,724: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-31 20:49:31,780: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-31 20:49:31,780: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-31 20:49:31,783: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 20:49:31,785: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 20:49:31,785: INFO: common: created directory at: artifacts]
[2025-05-31 20:49:31,786: INFO: common: created directory at: artifacts\training]
[2025-05-31 20:49:31,786: ERROR: main: "'ConfigBox' object has no attribute 'epochs'"]
Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'EPOCHS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'EPOCHS'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'EPOCHS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'EPOCHS'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'epochs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'epochs'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'epochs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 35, in <module>
    training_model.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 32, in main
    training_config = config.get_training_config()
  File "d:\e2e proj\src\cnnClassifier\config\configuration.py", line 90, in get_training_config
    params_epochs=params.EPOCHS,
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'epochs'"
[2025-05-31 20:54:57,663: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 20:54:57,672: INFO: helpers: Accessing as gourav7-7]
[2025-05-31 20:54:58,082: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/gourav7-7/E2E-Proj "HTTP/1.1 200 OK"]
[2025-05-31 20:54:58,455: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 20:54:58,455: INFO: helpers: Initialized MLflow to track repo "gourav7-7/E2E-Proj"]
[2025-05-31 20:54:58,455: INFO: helpers: Repository gourav7-7/E2E-Proj initialized!]
[2025-05-31 20:54:58,460: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-31 20:54:58,464: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 20:54:58,465: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 20:54:58,466: INFO: common: created directory at: artifacts]
[2025-05-31 20:54:59,585: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-31 20:54:59,656: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-31 20:54:59,759: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-31 20:54:59,761: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-31 20:54:59,763: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 20:54:59,763: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 20:54:59,763: INFO: common: created directory at: artifacts]
[2025-05-31 20:54:59,763: INFO: common: created directory at: artifacts\training]
[2025-05-31 20:54:59,971: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-05-31 20:55:00,577: ERROR: main: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.]
Traceback (most recent call last):
  File "d:\E2E Proj\main.py", line 35, in <module>
    training_model.main()
  File "d:\e2e proj\src\cnnClassifier\pipeline\stage_03_model_training.py", line 36, in main
    training.train()
  File "d:\e2e proj\src\cnnClassifier\components\training_data.py", line 93, in train
    self.model.fit(
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 3618, in _assert_compile_was_called
    raise RuntimeError(
RuntimeError: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.
[2025-05-31 21:11:28,222: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 21:11:28,222: INFO: helpers: Accessing as gourav7-7]
[2025-05-31 21:11:28,641: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/gourav7-7/E2E-Proj "HTTP/1.1 200 OK"]
[2025-05-31 21:11:29,035: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 21:11:29,045: INFO: helpers: Initialized MLflow to track repo "gourav7-7/E2E-Proj"]
[2025-05-31 21:11:29,045: INFO: helpers: Repository gourav7-7/E2E-Proj initialized!]
[2025-05-31 21:11:29,053: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-31 21:11:29,057: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 21:11:29,060: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 21:11:29,061: INFO: common: created directory at: artifacts]
[2025-05-31 21:11:30,175: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-31 21:11:30,175: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-31 21:11:30,175: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 21:11:30,175: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 21:11:30,179: INFO: common: created directory at: artifacts]
[2025-05-31 21:11:30,179: INFO: common: created directory at: artifacts\training]
[2025-05-31 21:39:48,681: INFO: main: >>>>>>>>>>>> Stage Model Training COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-31 21:39:48,681: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-31 21:39:48,685: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 21:39:48,687: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 21:39:48,687: INFO: common: created directory at: artifacts]
[2025-05-31 21:40:12,315: INFO: common: json file saved at: scores.json]
[2025-05-31 21:40:12,315: INFO: common: json file saved at: scores.json]
[2025-05-31 21:40:15,048: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 4 of 4). These functions will not be directly callable after loading.]
[2025-05-31 21:40:15,485: INFO: builder_impl: Assets written to: C:\Users\Gourav\AppData\Local\Temp\tmp38y0lrj9\model\data\model\assets]
[2025-05-31 21:40:53,902: INFO: main: >>>>>>>>>>>> Stage Model Evaluation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-31 22:15:58,256: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 22:15:58,269: INFO: helpers: Accessing as gourav7-7]
[2025-05-31 22:15:58,868: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/gourav7-7/E2E-Proj "HTTP/1.1 200 OK"]
[2025-05-31 22:15:59,483: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 22:15:59,484: INFO: helpers: Initialized MLflow to track repo "gourav7-7/E2E-Proj"]
[2025-05-31 22:15:59,492: INFO: helpers: Repository gourav7-7/E2E-Proj initialized!]
[2025-05-31 22:15:59,492: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-05-31 22:15:59,497: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 22:15:59,500: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 22:15:59,501: INFO: common: created directory at: artifacts]
[2025-05-31 22:16:00,699: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-31 22:16:00,699: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-31 22:16:00,699: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 22:16:00,713: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 22:16:00,713: INFO: common: created directory at: artifacts]
[2025-05-31 22:16:00,713: INFO: common: created directory at: artifacts\training]
[2025-05-31 23:02:40,704: INFO: main: >>>>>>>>>>>> Stage Model Training COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-31 23:02:40,704: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-05-31 23:02:40,704: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 23:02:40,704: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 23:02:40,704: INFO: common: created directory at: artifacts]
[2025-05-31 23:03:00,138: INFO: common: json file saved at: scores.json]
[2025-05-31 23:03:00,138: INFO: common: json file saved at: scores.json]
[2025-05-31 23:03:02,459: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 4 of 4). These functions will not be directly callable after loading.]
[2025-05-31 23:03:02,820: INFO: builder_impl: Assets written to: C:\Users\Gourav\AppData\Local\Temp\tmp5sof22ez\model\data\model\assets]
[2025-05-31 23:03:44,321: INFO: main: >>>>>>>>>>>> Stage Model Evaluation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-05-31 23:04:15,501: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 23:04:15,513: INFO: helpers: Accessing as gourav7-7]
[2025-05-31 23:04:16,181: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/gourav7-7/E2E-Proj "HTTP/1.1 200 OK"]
[2025-05-31 23:04:16,869: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 23:04:16,879: INFO: helpers: Initialized MLflow to track repo "gourav7-7/E2E-Proj"]
[2025-05-31 23:04:16,880: INFO: helpers: Repository gourav7-7/E2E-Proj initialized!]
[2025-05-31 23:04:16,885: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-31 23:04:16,888: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 23:04:16,889: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 23:04:16,889: INFO: common: created directory at: artifacts]
[2025-05-31 23:04:16,890: INFO: common: created directory at: artifacts\training]
[2025-05-31 23:06:43,185: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 23:06:43,197: INFO: helpers: Accessing as gourav7-7]
[2025-05-31 23:06:44,416: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/gourav7-7/E2E-Proj "HTTP/1.1 200 OK"]
[2025-05-31 23:06:45,234: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-31 23:06:45,241: INFO: helpers: Initialized MLflow to track repo "gourav7-7/E2E-Proj"]
[2025-05-31 23:06:45,241: INFO: helpers: Repository gourav7-7/E2E-Proj initialized!]
[2025-05-31 23:06:45,241: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-05-31 23:06:45,248: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-31 23:06:45,248: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-31 23:06:45,248: INFO: common: created directory at: artifacts]
[2025-05-31 23:06:45,248: INFO: common: created directory at: artifacts\training]
[2025-06-01 00:11:29,091: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-06-01 00:11:29,097: INFO: helpers: Accessing as gourav7-7]
[2025-06-01 00:11:29,533: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/gourav7-7/E2E-Proj "HTTP/1.1 200 OK"]
[2025-06-01 00:11:29,907: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-06-01 00:11:29,917: INFO: helpers: Initialized MLflow to track repo "gourav7-7/E2E-Proj"]
[2025-06-01 00:11:29,920: INFO: helpers: Repository gourav7-7/E2E-Proj initialized!]
[2025-06-01 00:11:29,929: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-06-01 00:11:29,931: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 00:11:29,933: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 00:11:29,934: INFO: common: created directory at: artifacts]
[2025-06-01 00:11:30,886: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-06-01 00:11:30,886: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-06-01 00:11:30,886: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 00:11:30,886: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 00:11:30,886: INFO: common: created directory at: artifacts]
[2025-06-01 00:11:30,886: INFO: common: created directory at: artifacts\training]
[2025-06-01 00:42:42,001: INFO: main: >>>>>>>>>>>> Stage Model Training COMPLETED <<<<<<<<<

X=========================================================X]
[2025-06-01 00:42:42,001: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-06-01 00:42:42,001: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 00:42:42,001: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 00:42:42,011: INFO: common: created directory at: artifacts]
[2025-06-01 00:43:04,976: INFO: common: json file saved at: scores.json]
[2025-06-01 00:43:04,977: INFO: common: json file saved at: scores.json]
[2025-06-01 00:43:07,571: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 3 of 3). These functions will not be directly callable after loading.]
[2025-06-01 00:43:08,046: INFO: builder_impl: Assets written to: C:\Users\Gourav\AppData\Local\Temp\tmpxq43s7xs\model\data\model\assets]
[2025-06-01 00:43:47,551: INFO: main: >>>>>>>>>>>> Stage Model Evaluation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-06-01 00:57:39,602: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-06-01 00:57:39,612: INFO: helpers: Accessing as gourav7-7]
[2025-06-01 00:57:40,034: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/gourav7-7/E2E-Proj "HTTP/1.1 200 OK"]
[2025-06-01 00:57:40,410: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-06-01 00:57:40,412: INFO: helpers: Initialized MLflow to track repo "gourav7-7/E2E-Proj"]
[2025-06-01 00:57:40,413: INFO: helpers: Repository gourav7-7/E2E-Proj initialized!]
[2025-06-01 00:57:40,421: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-06-01 00:57:40,423: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 00:57:40,425: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 00:57:40,426: INFO: common: created directory at: artifacts]
[2025-06-01 00:57:41,546: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-06-01 00:57:41,546: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-06-01 00:57:41,549: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 00:57:41,551: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 00:57:41,552: INFO: common: created directory at: artifacts]
[2025-06-01 00:57:41,553: INFO: common: created directory at: artifacts\training]
[2025-06-01 01:26:45,248: INFO: main: >>>>>>>>>>>> Stage Model Training COMPLETED <<<<<<<<<

X=========================================================X]
[2025-06-01 01:26:45,248: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-06-01 01:26:45,251: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 01:26:45,253: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 01:26:45,255: INFO: common: created directory at: artifacts]
[2025-06-01 01:27:18,458: INFO: common: json file saved at: scores.json]
[2025-06-01 01:27:18,460: INFO: common: json file saved at: scores.json]
[2025-06-01 01:27:20,950: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 3 of 3). These functions will not be directly callable after loading.]
[2025-06-01 01:27:21,545: INFO: builder_impl: Assets written to: C:\Users\Gourav\AppData\Local\Temp\tmputhjgjhr\model\data\model\assets]
[2025-06-01 01:27:57,584: INFO: main: >>>>>>>>>>>> Stage Model Evaluation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-06-01 01:39:11,402: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-06-01 01:39:11,408: INFO: helpers: Accessing as gourav7-7]
[2025-06-01 01:39:11,837: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/gourav7-7/E2E-Proj "HTTP/1.1 200 OK"]
[2025-06-01 01:39:12,238: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-06-01 01:39:12,240: INFO: helpers: Initialized MLflow to track repo "gourav7-7/E2E-Proj"]
[2025-06-01 01:39:12,242: INFO: helpers: Repository gourav7-7/E2E-Proj initialized!]
[2025-06-01 01:39:12,248: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-06-01 01:39:12,250: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 01:39:12,252: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 01:39:12,253: INFO: common: created directory at: artifacts]
[2025-06-01 01:39:13,414: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-06-01 01:39:13,415: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-06-01 01:39:13,416: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 01:39:13,418: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 01:39:13,418: INFO: common: created directory at: artifacts]
[2025-06-01 01:39:13,418: INFO: common: created directory at: artifacts\training]
[2025-06-01 02:05:15,403: INFO: main: >>>>>>>>>>>> Stage Model Training COMPLETED <<<<<<<<<

X=========================================================X]
[2025-06-01 02:05:15,403: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-06-01 02:05:15,403: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 02:05:15,403: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 02:05:15,403: INFO: common: created directory at: artifacts]
[2025-06-01 02:05:34,455: INFO: common: json file saved at: scores.json]
[2025-06-01 02:05:34,455: INFO: common: json file saved at: scores.json]
[2025-06-01 02:05:36,811: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 3 of 3). These functions will not be directly callable after loading.]
[2025-06-01 02:05:37,251: INFO: builder_impl: Assets written to: C:\Users\Gourav\AppData\Local\Temp\tmpr1xgi2hq\model\data\model\assets]
[2025-06-01 02:06:32,470: INFO: main: >>>>>>>>>>>> Stage Model Evaluation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-06-01 02:09:29,547: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-06-01 02:09:29,547: INFO: helpers: Accessing as gourav7-7]
[2025-06-01 02:09:29,983: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/gourav7-7/E2E-Proj "HTTP/1.1 200 OK"]
[2025-06-01 02:09:30,390: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-06-01 02:09:30,391: INFO: helpers: Initialized MLflow to track repo "gourav7-7/E2E-Proj"]
[2025-06-01 02:09:30,391: INFO: helpers: Repository gourav7-7/E2E-Proj initialized!]
[2025-06-01 02:09:30,402: INFO: main: >>>>>>>>>>>>>> Stage Model Preparation started <<<<<<<<<<<<<<]
[2025-06-01 02:09:30,403: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 02:09:30,406: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 02:09:30,406: INFO: common: created directory at: artifacts]
[2025-06-01 02:09:31,391: INFO: main: >>>>>>>>>>>> Stage Model Preparation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-06-01 02:09:31,391: INFO: main: >>>>>>>>>>>>>> Stage Model Training started <<<<<<<<<<<<<<]
[2025-06-01 02:09:31,391: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 02:09:31,391: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 02:09:31,391: INFO: common: created directory at: artifacts]
[2025-06-01 02:09:31,391: INFO: common: created directory at: artifacts\training]
[2025-06-01 02:33:31,346: INFO: main: >>>>>>>>>>>> Stage Model Training COMPLETED <<<<<<<<<

X=========================================================X]
[2025-06-01 02:33:31,346: INFO: main: >>>>>>>>>>>>>> Stage Model Evaluation started <<<<<<<<<<<<<<]
[2025-06-01 02:33:31,346: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 02:33:31,346: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 02:33:31,346: INFO: common: created directory at: artifacts]
[2025-06-01 02:33:52,809: INFO: common: json file saved at: scores.json]
[2025-06-01 02:33:52,809: INFO: common: json file saved at: scores.json]
[2025-06-01 02:33:55,470: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 3 of 3). These functions will not be directly callable after loading.]
[2025-06-01 02:33:55,946: INFO: builder_impl: Assets written to: C:\Users\Gourav\AppData\Local\Temp\tmplhp4vu_b\model\data\model\assets]
[2025-06-01 02:34:48,352: INFO: main: >>>>>>>>>>>> Stage Model Evaluation COMPLETED <<<<<<<<<

X=========================================================X]
[2025-06-01 10:13:27,508: INFO: stage_01_data_ingestion: >>>>>>>> stage Data Ingestion stage started here <<<<<<<<]
[2025-06-01 10:13:27,510: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 10:13:27,515: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 10:13:27,515: INFO: common: created directory at: artifacts]
[2025-06-01 10:13:27,515: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-01 10:13:27,516: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/kidney-ct-scan-image.zip]
[2025-06-01 10:16:20,902: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/kidney-ct-scan-image.zip]
[2025-06-01 10:16:40,235: INFO: stage_01_data_ingestion: >>>>>>>>> stage Data Ingestion stage completed <<<<<<<<<

X=======================================================X]
[2025-06-01 10:30:51,661: INFO: stage_01_data_ingestion: >>>>>>>> stage Data Ingestion stage started here <<<<<<<<]
[2025-06-01 10:30:51,661: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 10:30:51,661: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 10:30:51,661: INFO: common: created directory at: artifacts]
[2025-06-01 10:30:51,661: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-01 10:30:51,661: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/kidney-ct-scan-image.zip]
[2025-06-01 10:31:50,687: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zsI3e2QVpuhM1hjHMlr-8lx6os6X2UQF/view?usp=sharing into file artifacts/data_ingestion/kidney-ct-scan-image.zip]
[2025-06-01 10:32:09,902: INFO: data_ingestion: Moved Cyst to artifacts/data_ingestion/kidney-ct-scan-image\Cyst]
[2025-06-01 10:32:09,902: INFO: data_ingestion: Moved Normal to artifacts/data_ingestion/kidney-ct-scan-image\Normal]
[2025-06-01 10:32:09,902: INFO: data_ingestion: Moved Stone to artifacts/data_ingestion/kidney-ct-scan-image\Stone]
[2025-06-01 10:32:09,902: INFO: data_ingestion: Moved Tumor to artifacts/data_ingestion/kidney-ct-scan-image\Tumor]
[2025-06-01 10:32:09,902: INFO: data_ingestion: Cleaned up temporary extraction directory]
[2025-06-01 10:32:09,902: INFO: stage_01_data_ingestion: >>>>>>>>> stage Data Ingestion stage completed <<<<<<<<<

X=======================================================X]
[2025-06-01 10:35:34,425: INFO: stage_02_model_preparation: >>>>>>>> stage Model Preparation Stage started here <<<<<<<<]
[2025-06-01 10:35:34,433: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 10:35:34,433: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 10:35:34,433: INFO: common: created directory at: artifacts]
[2025-06-01 10:35:37,050: INFO: stage_02_model_preparation: >>>>>>>>> stage Model Preparation Stage completed <<<<<<<<<

X=======================================================X]
[2025-06-01 10:35:46,861: INFO: stage_03_model_training: >>>>>>>> stage Model Training Stage started here <<<<<<<<]
[2025-06-01 10:35:46,861: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 10:35:46,861: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 10:35:46,861: INFO: common: created directory at: artifacts]
[2025-06-01 10:35:46,861: INFO: common: created directory at: artifacts\training]
[2025-06-01 11:10:09,127: INFO: stage_03_model_training: >>>>>>>>> stage Model Training Stage completed <<<<<<<<<

X=======================================================X]
[2025-06-01 11:10:22,237: INFO: stage_04_model_eval: *******************]
[2025-06-01 11:10:22,238: INFO: stage_04_model_eval: >>>>>> stage Evaluation stage started <<<<<<]
[2025-06-01 11:10:22,240: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-01 11:10:22,242: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-01 11:10:22,242: INFO: common: created directory at: artifacts]
[2025-06-01 11:10:48,080: INFO: common: json file saved at: scores.json]
[2025-06-01 11:10:48,082: INFO: common: json file saved at: scores.json]
[2025-06-01 11:10:48,994: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 3 of 3). These functions will not be directly callable after loading.]
[2025-06-01 11:10:49,790: INFO: builder_impl: Assets written to: C:\Users\Gourav\AppData\Local\Temp\tmposa2gns2\model\data\model\assets]
[2025-06-01 11:11:03,108: INFO: stage_04_model_eval: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-06-01 11:53:41,597: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.224.106.194:8080]
[2025-06-01 11:53:41,597: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-01 11:53:51,066: ERROR: _internal: 10.224.106.194 - - [01/Jun/2025 11:53:51] code 400, message Bad request version ('êê\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06\x93ÊÊ\x00\x00\x00#\x00\x00\x00')]
[2025-06-01 11:53:51,067: INFO: _internal: 10.224.106.194 - - [01/Jun/2025 11:53:51] "[35m[1m\x16\x03\x01\x07\x00\x01\x00\x06ü\x03\x03Û\x83zPý\x1f1E>\x92 }\x9f\x85,¾@\x92\x04\x97\x11ìÐ9\x099P¼cå\x92ê ,Àh&}µ5gô\x8cV¥T\x02\x95\x02\x92ÃÈOu[ôõï\x85BÐ\x92³óÓ\x00 êê\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06\x93ÊÊ\x00\x00\x00#\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -]
[2025-06-01 11:53:51,070: ERROR: _internal: 10.224.106.194 - - [01/Jun/2025 11:53:51] code 400, message Bad request version ("Ø\x7fP\x86³ñ´\x1aº\x1an¶d¼=ª¹¢`ÿÐ'!")]
[2025-06-01 11:53:51,070: INFO: _internal: 10.224.106.194 - - [01/Jun/2025 11:53:51] "[35m[1m\x16\x03\x01\x06à\x01\x00\x06Ü\x03\x03á\x88á¸ßÏÅT>\x84»é\x0cN\x93>\x89Øõ}¸6`eZ\x93<\x91üÜï× Ø\x7fP\x86³ñ´\x1aº\x1an¶d¼=ª¹¢`ÿÐ'![0m" HTTPStatus.BAD_REQUEST -]
[2025-06-01 11:53:53,308: INFO: _internal: 10.224.106.194 - - [01/Jun/2025 11:53:53] "GET / HTTP/1.1" 200 -]
[2025-06-01 11:54:15,896: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "d:\E2E Proj\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "d:\e2e proj\src\cnnClassifier\pipeline\prediction.py", line 12, in predict
    model = load_model(os.path.join("artifacrs", "training", "model.h5"))
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Gourav\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\saving\save.py", line 226, in load_model
    raise IOError(
OSError: No file or directory found at artifacrs\training\model.h5
[2025-06-01 11:54:15,903: INFO: _internal: 10.224.106.194 - - [01/Jun/2025 11:54:15] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-01 11:58:03,106: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.224.106.194:8080]
[2025-06-01 11:58:03,106: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-01 11:58:08,122: INFO: _internal: 10.224.106.194 - - [01/Jun/2025 11:58:08] "GET / HTTP/1.1" 200 -]
[2025-06-01 11:58:21,291: INFO: _internal: 10.224.106.194 - - [01/Jun/2025 11:58:21] "POST /predict HTTP/1.1" 200 -]
[2025-06-02 23:07:49,349: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.224.106.194:8080]
[2025-06-02 23:07:49,349: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-02 23:07:56,161: INFO: _internal: 10.224.106.194 - - [02/Jun/2025 23:07:56] "GET / HTTP/1.1" 200 -]
[2025-06-02 23:07:57,235: INFO: _internal: 10.224.106.194 - - [02/Jun/2025 23:07:57] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
